### ISSUE TITLE
filter: Unhandled ParserError when reading metadata (`Expected 5 fields in line 89, saw 66`)

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#944] opened 2022-05-21 11:06 UTC
### Current Behavior
Filter throws an unhandled error when reading a metadata file. I'm not quite sure what's wrong with the file.

### Expected behavior
Error is handled and I get a human friendly message that mentions the file that could not be parsed (this is not visible at the moment)

### How to reproduce
Pass a metadata.tsv with inconsistent numbers of columns, more columns in last column than in previous ones.

Augur 15.0.2

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/augur/filter.py", line 1377, in run
    for metadata in metadata_reader:
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1187, in __next__
    return self.get_chunk()
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1284, in get_chunk
    return self.read(nrows=size)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1254, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/python_parser.py", line 270, in read
    alldata = self._rows_to_cols(content)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/python_parser.py", line 1013, in _rows_to_cols
    self._alert_malformed(msg, row_num + 1)
  File "/usr/local/Caskroom/mambaforge/base/envs/nextstrain/lib/python3.8/site-packages/pandas/io/parsers/python_parser.py", line 739, in _alert_malformed
    raise ParserError(msg)
pandas.errors.ParserError: Expected 5 fields in line 89, saw 66
```

**Comment by victorlin** [comment] 2024-05-22 17:48
Duplicate of #1195. The error is slightly different now but it's still an unhandled exception.

**Closed by victorlin** 2024-05-22 17:48 UTC
Labels: bug, duplicate
