### ISSUE TITLE
augur validate output isn't easily interpretable

### ISSUE THREAD

**Issue by crashfrog** [nextstrain/augur#440] opened 2020-02-05 17:36 UTC
```
$ augur version
augur 6.2.0
$ augur validate export-v2 senterica_aroC_5_dnaN_2_hemD_3_hisD_7_purE_6_sucA_6_thrA_11.json
Validation succeeded
Validating that the JSON is internally consistent
	WARNING:  The filter "location" does not appear as a property on any tree nodes.
	WARNING:  The filter "author" does not appear as a property on any tree nodes.
Validation failed
```

Hard to make sense of this output. Did validation succeed, or fail? (It exited with code `0`.) If it failed what was the failure? Are the warnings actually meant to be failures? Why don't `location` or `author` appear as properties on the nodes if they're part of the metadata file given to `augur export`?

**Comment by tsibley** [comment] 2020-02-10 20:18
Hi @crashfrog, thanks for this report. I agree the messages here are pretty confusing. Right now the validation code is a bit ad-hoc and messaging isn't unified. I've tried to clean up and clarify some of that in #441.

Although it's totally unclear, your file _did_ validate, but there were some non-critical warnings you might want to resolve regarding `location` and `author` filters which won't work because no nodes have those traits.

The nodes probably lacked those traits because although your metadata file given to `augur export v2` contained them, the export wasn't configured to pass them through using `--metadata-color-by`. See the [Traits section of Migrating from Augur v5 to v6](https://nextstrain-augur.readthedocs.io/en/stable/releases/migrating-v5-v6.html#id1). This is a new default to prevent slurping in all of the metadata file into the export, which is particularly important when the metadata file might contain both public and protected information, only some of which is allowed to make it into the exported JSONs. @emmahodcroft might be able to offer a more detailed diagnosis here too. If you need help resolving these warnings, please feel free to open a new issue with the full steps and files you used for running `augur export v2` so we can reproduce it.

**Comment by crashfrog** [comment] 2020-02-10 20:20
Thanks, that's helpful. I'll review the documentation you linked, I hadn't seen that before.

**Closed** 2020-02-25 23:12 UTC
