### ISSUE TITLE
Uncaught `KeyError` in `augur frequencies`

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [nextstrain/augur#1074] opened 2022-10-26 11:10 UTC
augur frequencies \
>   --metadata results/subsampled_metadata.tsv \
>   --tree results/tree.nwk \
>   --method kde \
>   --pivot-interval 1 \
>   --pivot-interval-units weeks \
>   --narrow-bandwidth 0.041 \
>   --proportion-wide 0.0 \
>   --output auspice/ncov_tip-frequencies.json
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/augur/__init__.py", line 65, in run
    return args.__command__.run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/augur/frequencies.py", line 103, in run
    tip.attr = {"num_date": np.mean(dates[tip.name])}
KeyError: 'MN908947'

An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>

**Comment by huddlej** [comment] 2022-11-02 19:23
This is a duplicate of https://github.com/blab/veme-2022/issues/1 where we will try to resolve it.

**Closed by huddlej** 2022-11-02 19:23 UTC
Labels: bug
