### ISSUE TITLE
Layering Auspice config files

### ISSUE THREAD

**Issue by genehack** [nextstrain/augur#1663] opened 2024-11-08 20:09 UTC
### Context
[Slack context](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1622071387034200?thread_ts=1622004897.033100&cid=C01LCTT7JNN)

### Description
Sort of regarding the auspice config stuff, it would be cool if we supported config merging or inheritance someday. For instance, if we had reasonable default auspice config we could pass to augur export along with a minimal custom config that overrides or sets just a couple of build-specific options (e.g., title, etc.) that could save a lot of copy/paste (or failing to copy/paste to all the possible copies when a new color-by is added) (from @huddlej in above Slack thread)

**Comment by jameshadfield** [comment] 2024-11-08 21:48
Largely a duplicate of https://github.com/nextstrain/augur/issues/298

**Comment by genehack** [comment] 2024-11-08 23:10
_sigh_ and I _searched_ for a previous issue, dammit, but not in the **AUGUR** repo... >_<

**Comment by tsibley** [comment] 2024-11-12 20:43
GitHub's org-wide search is nice for finding stuff precisely because of this problem. (Personally, I've defaulted to always using it, even if I'm pretty sure I know which repo something is in.)

**Comment by genehack** [comment] 2024-12-05 04:35
Closing as a dupe

**Closed** 2024-12-05 21:24 UTC
Labels: enhancement
