### ISSUE TITLE
Implement subsampling as a script (or eventually "augur subsample")

### ISSUE THREAD

**Issue by DSequ** [nextstrain/augur#805] opened 2021-12-08 19:54 UTC

**Comment by jameshadfield** [comment] 2021-12-08 20:03
Development was happening at https://github.com/nextstrain/ncov/pull/711 but it has stalled a bit

**Comment by sidneymbell** [comment] 2022-11-08 21:48
Update: we discussed this with the Nextstrain team last week, and while this is still very much of interest to both the Nextstrain team and users, it doesn't seem like the right time to dive into this work. For more context, [see the doc](https://docs.google.com/document/d/17IzCsLNat3ARV_JWxhLZbAM7cMdLrWsvFbRghujD3IM/edit?usp=sharing).

**Comment by victorlin** [comment] 2024-05-08 21:49
Duplicate of #635

**Closed by victorlin** 2024-05-08 21:49 UTC
Labels: duplicate, Epic
