### ISSUE TITLE
DEV(tests): Functional tests output files into git-tracked directory `tests/functional/tree`

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#977] opened 2022-06-17 14:31 UTC
### Current Behavior
Run `./run_tests.sh` and observe that output appears in the git tracked directory `tests/functional/tree`

<img width="993" alt="image" src="https://user-images.githubusercontent.com/25161793/174318977-35b968d4-3dc5-4226-96f0-1a6745636949.png">

**Comment by victorlin** [comment] 2022-06-17 18:05
Duplicate of #863

**Closed by victorlin** 2022-06-17 18:05 UTC
Labels: bug
