### ISSUE TITLE
DEV: Codecov often fails in CI

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1173] opened 2023-02-28 20:00 UTC
### Current Behavior
We regularly get codecov upload failing in our CI runs, e.g. today: https://github.com/nextstrain/augur/actions/runs/4295838115/jobs/7487020531#step:8:40

### Possible solution
Codecov recommends using a token as a workaround: https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954/14

**Comment by joverlee521** [comment] 2023-02-28 23:45
Duplicate of #1111

**Closed by joverlee521** 2023-02-28 23:45 UTC
Labels: bug
