### ISSUE TITLE
ENH: Allow generation of unique node ids in export

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1068] opened 2022-10-21 11:00 UTC
### Context
When sharing a tree, it's often useful to be able to point viewers to an exact node.

Node zooming of Auspice only works if there's a unique label or combination of labels that identifies the node in question.

It'd be nice if there was the option to generate such unique labels for a given Auspice tree in Augur.

This is one example implementation that does this: https://github.com/corneliusroemer/nextstrain-deploy/blob/main/deploy.py#L17-L25

Alternatives are to have Auspice generate the unique label on the fly, by hashing some property of an internal node.

Maybe it'd be better to generate this in Auspice and allow users to choose whether they want to share using that hash or not.

I think one reason we don't generate such a hash is that it would not be stable across trees. And we prefer to have stability across rebuilds.

We could solve this by having two hierarchies of zoom labels: a) (ideally) reproducible, based on mutations, and other branch labels, and b) a lower priority hash that is a fallback and works only on the exact tree.

**Comment by tsibley** [comment] 2022-10-21 22:45
I believe this is a duplicate of https://github.com/nextstrain/auspice/issues/1036, where there was much discussion and general consensus on a solution for this. No implementation yet, however.

**Closed** 2022-11-02 19:20 UTC
Labels: enhancement

**Comment by corneliusroemer** [comment] 2022-11-02 23:23
Thanks @tsibley for linking the previous discussion.

Both solutions require changes to `augur export` so it would make sense to have an issue in Augur for this - not (just) Auspice or transfer that issue here.
